# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_alias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('AliasPluginModel', 'AliasPlugin'),
        migrations.AlterField(
            model_name='aliasplugin',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_alias_aliasplugin', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
