# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-27 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_alias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='identifier',
            field=models.CharField(blank=True, help_text='To render the alias in templates.', max_length=255, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='djangocms_alias.Category'),
        ),
    ]
