# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 09:14
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion
import djangocms_alias.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_pagenode'),
        ('djangocms_alias', '0002_auto_20180412_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alias',
            old_name='placeholder',
            new_name='draft_content',
        ),
        migrations.AddField(
            model_name='alias',
            name='live_content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_draft', slotname=djangocms_alias.models._get_alias_placeholder_slot, to='cms.Placeholder'),
        ),
        migrations.AlterField(
            model_name='alias',
            name='draft_content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alias_draft', slotname=djangocms_alias.models._get_alias_placeholder_slot, to='cms.Placeholder'),
        ),
    ]
