# Generated by Django 3.2.20 on 2023-07-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_alias', '0002_auto_20200723_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='name',
            field=models.CharField(max_length=120, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='categorytranslation',
            unique_together={('language_code', 'master'), ('name', 'language_code')},
        ),
    ]
