# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_alias', '0003_auto_20180413_1114'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alias',
            unique_together=set([('name', 'category')]),
        ),
    ]
