# Generated by Django 5.2.3 on 2025-07-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangocms_alias", "0005_dynamic_slot_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alias",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="aliascontent",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="categorytranslation",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
