PLUGIN_URL_NAME_PREFIX = 'djangocms_alias'

CREATE_ALIAS_URL_NAME = '{}_create'.format(PLUGIN_URL_NAME_PREFIX)
PUBLISH_ALIAS_URL_NAME = '{}_publish'.format(PLUGIN_URL_NAME_PREFIX)
DELETE_ALIAS_PLUGIN_URL_NAME = '{}_delete'.format(PLUGIN_URL_NAME_PREFIX)
DETACH_ALIAS_PLUGIN_URL_NAME = '{}_detach_plugin'.format(PLUGIN_URL_NAME_PREFIX)  # noqa: E501
DETAIL_ALIAS_URL_NAME = '{}_detail'.format(PLUGIN_URL_NAME_PREFIX)
LIST_ALIASES_URL_NAME = '{}_list'.format(PLUGIN_URL_NAME_PREFIX)
CATEGORY_LIST_URL_NAME = '{}_category_list'.format(PLUGIN_URL_NAME_PREFIX)

DRAFT_ALIASES_QUERY_KEY = 'draft_aliases'
